/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hispanolauncher;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author inuckles
 */
public class Panel_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Inicio
     */
    public Panel_Inicio() {
       
        
        initComponents();
        
        
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        pnlInicio = new javax.swing.JPanel();

        lblInicio.setBackground(new java.awt.Color(0, 0, 0));
        lblInicio.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(238, 238, 238));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");

        pnlInicio.setForeground(new java.awt.Color(255, 255, 255));
        pnlInicio.setOpaque(false);

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
        public void log(String texto){
            
                String rutaLog = System.getenv("APPDATA") + "\\.hispano_launcher\\logs\\";
                File dirLog = new File(rutaLog);
                boolean existeDir = dirLog.exists();
                if (existeDir){
                    
                }else{
                    if (dirLog.mkdir()){
                       
                    }else{
                         JOptionPane.showMessageDialog(null,"Error al crear la carpeta de logs.");
                    }
                }
                    
                
                
                
                Date fecha = new Date(); 
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-YYYY");
                SimpleDateFormat formato2 = new SimpleDateFormat("dd/MM/YYYY HH:mm a");
                String fechaFormateada = formato.format(fecha);
                String fechaFormateada2 = formato2.format(fecha);
                String nombreLog = "log_"+ fechaFormateada + ".txt";
                FileWriter myWriter; 
                try {
                    myWriter = new FileWriter(rutaLog + nombreLog,true); 
                    myWriter.write("[" + fechaFormateada2 +  "] " + texto + "\n");
                    myWriter.close();
                } catch (IOException ex) {
                    Logger.getLogger(Panel_Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
                
        }       
                
        
        
                 
                 
                
                
                
                
        
    
      


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblInicio;
    private javax.swing.JPanel pnlInicio;
    // End of variables declaration//GEN-END:variables
}
