/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hispanolauncher;

/**
 *
 * @author inuckles
 * 
 * 
 * 
 */


    import java.awt.Graphics;
    import java.awt.Image;
    import javax.swing.ImageIcon;
public class Panel_Inicio2 extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Panel_Inicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloInicio = new javax.swing.JLabel();

        lblTituloInicio.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTituloInicio.setForeground(new java.awt.Color(238, 238, 238));
        lblTituloInicio.setText("Inicio");

        setBackground(new java.awt.Color(84, 84, 84));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTituloInicio;
    // End of variables declaration//GEN-END:variables
}
